name: Reusable Deploy Code
on:
  workflow_call:
    inputs:
      artifact-name:
        description: We require artifact name
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Output Contents
        run: ls
      - name: Deploy
        run: echo "Deploying...."
